# For full list of configuration elements see documentation at https://docs.astral.sh/ruff/editors/settings.

line-length = 160
src = [
    'ebm',
    'ebmgeodist'
]

[format]
quote-style = "single"
indent-style = "space"
docstring-code-format = true

# For full list of available rules check documentation at https://docs.astral.sh/ruff/rules/.
[lint]
select = [ # Use listed rules for all files
    "A", # flake8-builtins
    "ANN", # flake8-annotations
    "ASYNC", # flake8-async
    "B", # flake8-bugbear
    "C90", # mcabe
    "COM", # flake8-commas
    "E", # pycodestyle
    "EM", # flake8-errmsg
    "F", # pyflakes
    "FIX", #flake8-fixme
    "G", # flake8-logging-format
    "I", # isort
    "INP", # flake8-no-pep420
    "ISC", # flake8-implicit-str-concat
    "N", # pep8-naming
    "PD", # pandas-vet
    "PLC", # pylint
    "PLE", # pylint
    "PLR", # pylint
    "PLW", # pylint
    "PT", # flake8-pytest-style
    "PTH", # flake-use-pathlib
    "Q", # flake8-quotes
    "RET", # flake8-return
    "RSE", # flake8-raise
    "RUF", # ruff-specific-rules
    "SIM", # flake8-simplify
    "SLF", # flake8-self
    "UP", # pyupgrade
    "W" # pycodestyle
]

ignore = [ # except ignore listed rules for all files
    'ANN204', # missing docstring in public package
    'B007', # unused loop control variable
    'COM819', # prohibited trailing comma in function call with single argument
    'N999', # invalid module name
    'D203', # incorrect blank line before class docstring
    'D212', # multi-line summary first line
    'D104', # undocumented public package
    'D100', # undocumented public module
    'INP001', # implicit namespace package
    'EM101', # raw string in exception
    'FIX002', # line containes todo
    'PLR0912', # too many branches
    'PLR0913', # too many arguments
    'SIM108', # if-else-block insteaed of if exp
    'Q000', # bad quotes inline string
    'RET504', # unnecessary assign
    'W293'#blank line with whitespace
]

[lint.isort]
case-sensitive = true
no-lines-before = ["future", "standard-library"]
known-first-party = [
    'ebm',
    'ebmgeodist'
]

[lint.per-file-ignores]
"test_*.py" = [ # also ignore listed rules for test files
    "ANN201", # missing-return-type-undocumented-public-function
    "D103", # undocumented-public-function
    "PLR2004", # magic-value-comparison
    "ANN001", # missing-type-function-argument
    "SLF001"# private-member-access
]
"**/__init__.py" = ["I001"]
