
trigger:
  branches:
    include:
      - main

jobs:
- job: PushToGitHub
  displayName: 'Push Azure DevOps repo to GitHub'
  pool:
    vmImage: 'ubuntu-latest'
  variables:
    - name: pythonversion
      value: '3.11'
    - name: email
      value: 'ebm@nve.no'
  steps:
    - task: UsePythonVersion@0
      inputs:
        versionSpec: '$(pythonversion)'
      displayName: 'Use Python $(pythonversion) 🐍'
    - checkout: self
      persistCredentials: true
      fetchTags: true
      fetchDepth: 0
      displayName:  'Checkout ebm ⚡'

    - template: template-pytest-tasks.yml

    - template: template-push-to-github.yml
      parameters:
        remote_branch: '$(Build.SourceBranchName)'
        GIT_USER_EMAIL: 'kenord@nve.no'
