
trigger:
  branches:
    include:
      - dev

jobs:
- job: energibruksmodell-push-github-dev
  # Push Azure DevOps repo to GitHub
  displayName: 'Push Azure DevOps repo to GitHub'
  pool:
    vmImage: 'ubuntu-latest'
  variables:
    - name: pythonversion
      value: '3.11'
    - name: email
      value: 'ebm@nve.no'
  steps:
    - task: UsePythonVersion@0
      inputs:
        versionSpec: '$(pythonversion)'
      displayName: 'Use Python $(pythonversion) 🐍'

    - checkout: self
      fetchTags: true
      fetchDepth: 0
      displayName:  'Checkout ebm ⚡'
      # Set fetchDepth to 0 to ensure the full Git history is available.
      # Required for operations that rely on commit history, such as changelogs, versioning, or pushing to remote.

    - template: template-pytest-tasks.yml

    - template: template-push-to-github.yml
      parameters:
        remote_branch: '$(Build.SourceBranchName)'
        GIT_USER_EMAIL: 'kenord@nve.no'
