trigger:
  branches:
    include:
      - main
  paths:
    include:
      - ebm/__version__.py
pool:
  vmImage: 'ubuntu-latest'

variables:
  - name: pythonversion
    value: '3.11'
steps:
  - checkout: self
    fetchTags: true
    displayName:  'Checkout ebm ⚡'

  - task: UsePythonVersion@0
    inputs:
      versionSpec: '$(pythonversion)'
    displayName: 'Use Python $(pythonversion)'

  - template: template-pytest-tasks.yml

  - template: template-twine-upload.yml
